name: Inject commit hash into version.txt

on:
  push:
    branches:
      - main

jobs:
  inject-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get short commit hash
        id: get_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Write version
        run: echo "${{ steps.get_hash.outputs.hash }}" > version.txt

      - name: Commit version.txt
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.txt
          git commit -m "Update version to $(cat version.txt)" || echo "No changes to commit"
          git push
