name: Inject version number into version.txt

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Read current version
        id: read_version
        run: |
          if [ -f version.txt ]; then
            version=$(cat version.txt)
          else
            version=0
          fi
          echo "Current version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          new_version=$(( ${{ env.version }} + 1 ))
          echo $new_version > version.txt
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Commit and push version.txt
        run: |
          git add version.txt
          git commit -m "Bump version to ${{ env.new_version }}"
          git push
