name: Inject version number into version.txt

on:
  push:
    branches:
      - main

permissions:
  contents: write   # ✅ allow the workflow to push commits

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Read current version
        id: read_version
        run: |
          if [ -f version.txt ]; then
            version=$(cat version.txt)
          else
            version=0
          fi
          echo "version=$version" >> $GITHUB_ENV
          echo "Current version: $version"

      - name: Increment version
        run: |
          new_version=$(( ${{ env.version }} + 1 ))
          echo $new_version > version.txt
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "New version: $new_version"

      - name: Commit and push version.txt
        run: |
          git add version.txt
          git commit -m "Bump version to ${{ env.new_version }}" || echo "No changes to commit"
          git push origin HEAD:main
